before:
  hooks:
  - go mod download
builds:
- id: kubectl-advise-psp
  main: ./
  binary: kubectl-advise-psp
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

archives:
- builds:
  - kubectl-advise-psp
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE
