apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
  namespace: psp-test 
spec:
  serviceAccountName: psp-test-sa
  containers:
  - name: my-busybox-container
    image: busybox
    args: ["sleep", "3000"]
    securityContext:
      privileged: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - SYS_CHROOT
  hostPID: false
  hostIPC: false
  hostNetwork: false
