#!/bin/sh

set -eux

# run unit test before build
go test ./...

export GO111MODULE=on

$GOPATH/bin/goimports -w $(find . -type f -name '*.go' -not -path "./vendor/*") || true

env GOOS=$(uname -s | tr '[:upper:]' '[:lower:]') GOARCH=amd64 go build -a
