#!/bin/sh

set -eux

export GO111MODULE=on

RELEASE="v$(cat version)"

$GOPATH/bin/goimports -w $(find . -type f -name '*.go' -not -path "./vendor/*") || true

# build release for MacOS
env GOOS=darwin GOARCH=amd64 go build -a -o kubectl-advise-psp

tar -cvzf kubectl-advise-psp_${RELEASE}_darwin_amd64.tar.gz kubectl-advise-psp LICENSE

rm kubectl-advise-psp

# build release for Linux
env GOOS=linux GOARCH=amd64 go build -a -o kubectl-advise-psp

tar -cvzf kubectl-advise-psp_${RELEASE}_linux_amd64.tar.gz kubectl-advise-psp LICENSE

rm kubectl-advise-psp
